// Package duckdbkeys holds DuckDB's built-in core and community signing keys (spec 0009), as the
// pin has them (extension_helper.cpp, public_keys and community_public_keys). They are generated by
// `make reserved`; CI checks they are current.
package duckdbkeys

import (
	"crypto/rsa"
	_ "embed"
	"fmt"
	"regexp"

	"github.com/hugr-lab/duckdb-extension-repository/internal/extfile"
)

var (
	//go:embed core.pem
	corePEM string
	//go:embed community.pem
	communityPEM string

	pemRE = regexp.MustCompile(`(?s)-----BEGIN PUBLIC KEY-----\n.*?-----END PUBLIC KEY-----`)

	core      = mustParse("core", corePEM)
	community = mustParse("community", communityPEM)
)

func mustParse(name, s string) []*rsa.PublicKey {
	var out []*rsa.PublicKey
	for _, p := range pemRE.FindAllString(s, -1) {
		k, err := extfile.ParsePublicKey(p)
		if err != nil {
			panic(fmt.Sprintf("duckdbkeys: a %s key: %v", name, err))
		}
		out = append(out, k)
	}
	if len(out) == 0 {
		panic("duckdbkeys: no " + name + " keys")
	}
	return out
}

// Core returns DuckDB's core signing keys.
func Core() []*rsa.PublicKey { return core }

// Community returns DuckDB's community signing keys.
func Community() []*rsa.PublicKey { return community }
