version: "2"
linters:
  default: standard # errcheck, govet, ineffassign, staticcheck, unused
  settings:
    errcheck:
      exclude-functions:
        - (*os.File).Close
        - (*database/sql.DB).Close
        - (*database/sql.Rows).Close
        - (*github.com/hugr-lab/duckdb-extension-repository/internal/store.Store).Close
        - (*text/tabwriter.Writer).Flush
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
  exclusions:
    rules:
      - path: _test\.go
        linters: [errcheck]
