// Package reserved holds the extension names DuckDB owns (spec 0008): core names from the DuckDB
// pin, community names from duckdb/community-extensions at a pinned commit, and a curated extra list.
// The lists are generated by `make reserved` and only ever grow: a name that was reserved stays
// reserved, since clients may have installed it.
package reserved

import (
	_ "embed"
	"strings"
)

// Kinds of reserved names.
const (
	Core      = "core"
	Community = "community"
)

var (
	//go:embed core.txt
	coreList string
	//go:embed community.txt
	communityList string
	//go:embed extra.txt
	extraList string

	kinds = load()
)

func load() map[string]string {
	m := map[string]string{}
	for kind, list := range map[string]string{Community: communityList, Core: coreList + "\n" + extraList} {
		for _, line := range strings.Split(list, "\n") {
			if n := strings.TrimSpace(line); n != "" && !strings.HasPrefix(n, "#") {
				if m[n] != Core { // a name in both lists is core
					m[n] = kind
				}
			}
		}
	}
	return m
}

// Kind returns core or community for a reserved name, and "" for any other.
func Kind(name string) string { return kinds[name] }
