// Package blob stores extension bodies as content-addressed precompressed streams in a pluggable
// object store, and serves channel files from them with every byte verified (spec 0005).
package blob

import (
	"context"
	"errors"
	"fmt"
	"io"
	"regexp"
	"strings"
	"time"
)

// Store is an object store. Keys are generated by kista and validated by every backend (ValidKey).
type Store interface {
	// Put stores a complete object; it becomes visible only when complete and replaces any existing
	// object with the key.
	Put(ctx context.Context, key string, r io.ReaderAt, size int64) error
	// Get reads n bytes from off (n < 0: to the end).
	Get(ctx context.Context, key string, off, n int64) (io.ReadCloser, error)
	// Stat returns an object's size, or ErrNotFound.
	Stat(ctx context.Context, key string) (int64, error)
	Delete(ctx context.Context, key string) error
	// List calls fn for every object under prefix ("streams/" or "tmp/").
	List(ctx context.Context, prefix string, fn func(key string, size int64, modified time.Time) error) error
	// Anonymous reports whether key can be read without credentials (a public store), when the
	// backend can tell; ok is false when it cannot.
	Anonymous(ctx context.Context, key string) (readable, ok bool)
	// ID identifies the store (kind, endpoint or account, bucket or root, prefix) for domain pinning.
	ID() string
}

// Errors.
var (
	ErrNotFound = errors.New("blob: not found")
	ErrKey      = errors.New("blob: invalid key")
	ErrCorrupt  = errors.New("blob: stored stream does not match its record")
	ErrDomain   = errors.New("blob: storage domain refused")
)

// MarkerKey is the domain marker object.
const MarkerKey = "kista-domain.json"

var (
	streamKey = regexp.MustCompile(`^streams/[0-9a-f]{64}$`)
	tmpKey    = regexp.MustCompile(`^tmp/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$`)
	prefixRe  = regexp.MustCompile(`^([a-z0-9][a-z0-9_-]{0,62}/){0,4}$`)
)

// ValidKey checks a key against the grammar: streams/<64 hex>, tmp/<uuid>, or the marker.
func ValidKey(key string) error {
	if key == MarkerKey || streamKey.MatchString(key) || tmpKey.MatchString(key) {
		return nil
	}
	return fmt.Errorf("%w: %q", ErrKey, key)
}

// ValidListPrefix checks a List prefix.
func ValidListPrefix(p string) error {
	if p == "streams/" || p == "tmp/" {
		return nil
	}
	return fmt.Errorf("%w: list prefix %q", ErrKey, p)
}

// ValidPrefix checks a configured store prefix: empty, or lowercase segments each ending in "/".
func ValidPrefix(p string) error {
	if !prefixRe.MatchString(p) || strings.Contains(p, "..") {
		return fmt.Errorf("%w: prefix %q (lowercase segments ending with /)", ErrKey, p)
	}
	return nil
}

// StreamKey is the key of a stream.
func StreamKey(streamHash string) string { return "streams/" + streamHash }
